name: Python CI  # Nombre del workflow (puede ser cualquier cosa)

# Cuándo debe ejecutarse este workflow:
on:
  push:             # Se activa cuando hacés push
    branches: [main]  # Solo en la rama "main"
  pull_request:     # También cuando alguien hace un PR a main
    branches: [main]

# Qué trabajos debe hacer el workflow:
jobs:
  build:             # Nombre del trabajo
    runs-on: ubuntu-latest  # Sistema operativo del runner (puede ser Windows o macOS también)

    steps:           # Pasos a seguir
    - name: Checkout code
      uses: actions/checkout@v4  # Clona tu repo en el runner

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'   # Elegí la versión de Python

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests with pytest
      run: |
        pytest
    - name: Lint with pylint
      run: |
        pip install pylint
        pylint my_project
